# Navbar Menus
[[nav]]
  name    = "Accueil"
  url     = "/"
  weight  = 1
[[nav]]
  name    = "À propos"
  url     = "about"
  weight  = 2
[[nav]]
  name    = "Actualités"
  url     = "newsroom"
  weight  = 3
[[nav]]
  name   = "Champions"
  url     = "vote"
  weight  = 4