# Banner Section
[banner]
enable                = true
background_image      = "/images/backgrounds/hackathon-visuels.jpeg"
heading               = ""
tagline               = ""
primary_button        = "À propos"
primary_button_url    = "about"
secondary_button      = "Champions"
secondary_button_url  = "vote"

[call_to_action]
enable              = true
background_image    = "images/backgrounds/cta-background.jpg"
title               = "Ne soyez pas timide ! votez pour quelqu'un."
primary_button      = "Champions"
primary_button_url  = "vote"

[newsroom]
enable    = true
title     = "ACTUALITÉS"
subtitle  = "Retrouvez toute l'actualité sur le Prix AfricTivistes pour l'Action Civique"

[press]
enable    = true
title     = "LA PRESSE EN PARLE"
subtitle  = ""

[comitejury]
enable    = true
title     = "COMITÉ DE SÉLECTION / JURY FINAL"
subtitle  = ""


[footer]
# Footer Contact Info
[footer.contactInfo]
    title   = "Informations de contact"
    address = "AfricTivistes, BP : 19968 (Sénégal)"
    phone   = "(+221) 33 837 51 24"
    email   = "innov4democracy@africtivistes.org"
    # Footer Sitemap
    [footer.sitemap]
    title   = "Sitemap"
    [[footer.sitemap.link]]
        name = "Accueil"
        url  = "/"
    [[footer.sitemap.link]]
        name = "À propos"
        url  = "about"
    [[footer.sitemap.link]]
        name = "Actualités"
        url  = "newsroom"
    [[footer.sitemap.link]]
        name = "Champions"
        url  = "vote"
    # Footer Social Media
    [footer.social]
    title   = "Social Media"
    [[footer.social.link]]
        name = "Twitter"
        url  = "https://twitter.com/AFRICTIVISTES"
    [[footer.social.link]]
        name = "Facebook"
        url  = "https://www.facebook.com/africtivistes/"
    # Footer Service
    [footer.service]
    title       = "#Innov4Democracy"
    description = "Reconnaitre les Innovateurs au service de la démocratie !"